Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.3
  Include:
    - lib/**/*.rb
    - app/**/*.rb
    - spec/**/*.rb
  Exclude:
    - bin/**/*
    - spec/dummy/bin/**/*
    - spec/dummy/db/**/*
    - spec/dummy/config/**/*
    - doc/**/*

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 100
