Rails:
  Enabled: true

AllCops:
  Include:
    - lib/**/*.rb
    - app/**/*.rb
    - spec/**/*.rb
  Exclude:
    - bin/**/*
    - spec/dummy/bin/**/*
    - spec/dummy/db/**/*
    - spec/dummy/config/**/*

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100
